import initScroll from './modules/scroll-suave.js';
import initTabNav from './modules/tab-nav.js';
import initAccordion from './modules/accordion.js';
import initAnimacaoScroll from './modules/anima-scroll.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/initDropdownMenu.js';
import initMobileMenu from './modules/mobile-menu.js';
import initAnimaNumeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/initFuncionamento.js';

initTabNav();
initAccordion();
initScroll();
initAnimacaoScroll();
initModal();
initTooltip();
initDropdownMenu();
initMobileMenu();
initAnimaNumeros();
initFuncionamento();